"""refactor logic groups

Revision ID: 56feb37cd924
Revises: c7862dde220a
Create Date: 2026-03-15 14:22:38.871499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56feb37cd924'
down_revision: Union[str, Sequence[str], None] = 'c7862dde220a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupMembers', 'is_kicked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupMembers', sa.Column('is_kicked', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
