"""migration matchs players

Revision ID: ce055ae81cf9
Revises: 76774faa3be3
Create Date: 2026-03-15 16:29:51.109015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce055ae81cf9'
down_revision: Union[str, Sequence[str], None] = '76774faa3be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_id'), 'match_events', ['id'], unique=False)
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('longest_road', sa.Boolean(), nullable=True),
    sa.Column('longest_army', sa.Boolean(), nullable=True),
    sa.Column('thief_moves', sa.Integer(), nullable=True),
    sa.Column('city_count', sa.Integer(), nullable=True),
    sa.Column('village_count', sa.Integer(), nullable=True),
    sa.Column('roads_built', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_players_id'), 'match_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_players_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index(op.f('ix_match_events_id'), table_name='match_events')
    op.drop_table('match_events')
    # ### end Alembic commands ###
